-- Core/Defaults.lua
local ADDON_NAME, ETBC = ...

ETBC.defaults = {
  profile = {
    general = {
      enabled = true,
      minimap = { enabled = true, hide = false },
      ui = { theme = "WarcraftGreen", scale = 1.0, lock = false },
      debug = false,
    },

    mouse = {
      enabled = true,
      autoloot = false,
      autorepair = false,
      focusOnAltClick = true,
      cursor = {
        highlight = true,
        highlightSize = 18,
        highlightAlpha = 0.35,
        highlightColor = { r = 0.2, g = 1.0, b = 0.2, a = 1.0 },
      },
    },
	
	    minimapPlus = {
      enabled = true,

      sinkEnabled = true,
      locked = false,
      scale = 1.0,
      buttonSize = 28,
      padding = 6,
      columns = 6,
      growDown = true,
      backdrop = true,
      autoScan = true,
      scanInterval = 2.0,

      includeQueue = false,
      includeTracking = false,
      includeCalendar = false,
      includeClock = false,
      includeMail = false,
      includeDifficulty = false,

      squareMinimap = false,
      squareSize = 140,
      customDifficultyIcon = true,

      hideMinimapToggleButton = true,
      hideBagsBar = false,
      hideMicroMenu = false,
      hideQuickJoinToast = true,
      hideRaidToolsInParty = true,

      landingButtons = {
        ExpansionLandingPageMinimapButton = true,
        GarrisonLandingPageMinimapButton = true,
        QueueStatusMinimapButton = true,
      },

      quickEnabled = true,
      defaultLootMethod = "group",
      defaultLootThreshold = 2,

      sinkPoint = "TOPRIGHT",
      sinkRelPoint = "TOPRIGHT",
      sinkX = -200,
      sinkY = -120,
    },

    tooltip = {
      enabled = true,
      classColorNames = true,
      showGuild = true,
      showTarget = true,
      showItemId = true,
      showSpellId = true,
      showItemLevel = true,
      showVendorPrice = true,
      showStatSummary = true,
      statSummaryMax = 6,
      anchorMode = "DEFAULT",
      offsetX = 16,
      offsetY = -16,
      scale = 1.0,
      skin = {
        enabled = true,
        bg = { r = 0.03, g = 0.06, b = 0.03, a = 0.92 },
        grad = { r = 0.10, g = 0.35, b = 0.10, a = 0.22 },
        border = { r = 0.20, g = 1.00, b = 0.20, a = 0.95 },
      },
      healthBar = {
        enabled = true,
        classColor = true,
        color = { r = 0.2, g = 1.0, b = 0.2, a = 1.0 },
      },
    },

    sound = {
      enabled = true,
      muteAll = false,
      _saved = nil,
      _synced = nil,
      muteInBackground = false,
      errorSpeech = { enabled = true },
      volumes = { master = 1.0, sfx = 1.0, music = 0.6, ambience = 0.7, dialog = 0.8 },
      enableMusic = true,
      enableAmbience = true,
      enableSFX = true,
    },

    friends = {
      enabled = true,
      colorByClass = true,
      colorOffline = { r = 0.45, g = 0.45, b = 0.45, a = 1.0 },
      colorOnline = { r = 0.2, g = 1.0, b = 0.2, a = 1.0 },
      showLevel = true,
      showZone = true,
    },

    chatim = { enabled = true },
    gcdbar = { enabled = true },

    auras = {
      enabled = true,
      preview = false,
      playerOnly = false,
      useBlizzardTooltips = true,
      showMoveHandles = false,
      moveSnapToGrid = true,
      sortMode = "TIME",
      sortAscending = true,
      showCooldownSpiral = true,
      showDurationText = false,
      durationText = { font = "Friz Quadrata TT", size = 12, outline = "OUTLINE" },
      border = {
        enabled = true,
        color = { r = 0.15, g = 0.30, b = 0.15, a = 1.0 },
        debuffTypeColors = true,
      },
      buffs = {
        enabled = true,
        iconSize = 28,
        spacing = 6,
        perRow = 12,
        growthX = "LEFT",
        growthY = "DOWN",
        anchor = { point = "TOPRIGHT", relPoint = "TOPRIGHT", x = -240, y = -190 },
      },
      debuffs = {
        enabled = true,
        iconSize = 28,
        spacing = 6,
        perRow = 10,
        growthX = "LEFT",
        growthY = "DOWN",
        anchor = { point = "TOPRIGHT", relPoint = "TOPRIGHT", x = -240, y = -260 },
      },
    },

    actiontracker = {
      enabled = true,
      preview = false,
      trackSpells = true,
      trackItems = false,
      onlyPlayer = true,
      onlyInCombat = false,
      maxEntries = 10,
      lifetime = 12,
      iconSize = 32,
      spacing = 6,
      perRow = 10,
      growthX = "LEFT",
      growthY = "DOWN",
      anchor = { point = "CENTER", relPoint = "CENTER", x = 0, y = -220 },
      border = { enabled = true, color = { r = 0.15, g = 0.30, b = 0.15, a = 1.0 } },
      showCooldownSpiral = true,
      showName = false,
      nameText = {
        font = "Friz Quadrata TT",
        size = 12,
        outline = "OUTLINE",
        classColor = true,
        color = { r = 0.9, g = 0.9, b = 0.9, a = 1.0 },
      },
    },

    combattext = {
      enabled = true,
      preview = false,
      onlyInCombat = false,
      trackOutgoing = true,
      trackIncoming = false,
      showDirection = false,
      splitDirections = true,
      showDamage = true,
      showHeals = true,
      showMisses = true,
      showInterrupts = true,
      showDispels = false,
      showSpellName = false,
      showOverheal = false,
      throttleWindow = 0.12,
      maxLines = 10,
      floatDirection = "UP",
      floatDistance = 70,
      duration = 1.10,
      fadeStart = 0.55,
      randomX = 0,
      font = "Friz Quadrata TT",
      size = 18,
      outline = "THICKOUTLINE",
      shadow = true,
      classColor = false,
      useDamageColors = true,
      useSchoolColors = false,
      overrideColor = { r = 0.2, g = 1.0, b = 0.2, a = 1.0 },
      crit = {
        enabled = true,
        scale = 1.25,
        useCritColor = true,
        color = { r = 1.0, g = 0.80, b = 0.20, a = 1.0 },
      },
      blizzard = {
        disableBlizzardFCT = true,
        restoreOnDisable = true,
        _saved = nil,
      },
      anchor = { point = "CENTER", relPoint = "CENTER", x = 0, y = 120 },
    },

    vendor = {
      enabled = true,
      bypassWithShift = true,
      autoRepair = true,
      useGuildRepair = true,
      repairThreshold = 0,
      autoSellJunk = true,
      includeUnsellable = false,
      confirmHighValue = true,
      confirmMinValue = 200000,
      printSummary = true,
      throttle = { enabled = true, interval = 0.03, maxPerTick = 6 },
      whitelist = { enabled = false, items = {} },
      blacklist = { enabled = true, items = {} },
      maxQualityToSell = 0,
      skipLocked = true,
    },

    mailbox = {
      enabled = true,
      bypassWithShift = true,
      autoCollect = true,
      collectGold = true,
      collectItems = true,
      skipCOD = true,
      skipGM = false,
      skipAH = false,
      onlyOpenWhenEmpty = true,
      autoDeleteEmpty = false,
      confirmDelete = true,
      throttle = { enabled = true, interval = 0.05, maxPerTick = 3 },
      printSummary = true,
      _saved = nil,
    },

    -- VISIBILITY (NEW MAX)
    visibility = {
      enabled = true,
      throttle = 0.05,
      presets = {},
      editor = {},

      -- global master conditions (apply to modules that opt into visibility)
      global = {
        enabled = true,
        inCombat = false,       -- only show/run in combat
        outOfCombat = false,    -- only show/run out of combat
        inInstance = false,
        inRaid = false,
        inParty = false,
        solo = false,
        inBattleground = false,
      },

      -- per-module overrides (if override.enabled = true, it replaces global)
      modules = {
        auras = { enabled = false, inCombat = false, outOfCombat = false, inInstance = false, inRaid = false, inParty = false, solo = false, inBattleground = false },
        actiontracker = { enabled = false, inCombat = false, outOfCombat = false, inInstance = false, inRaid = false, inParty = false, solo = false, inBattleground = false },
        combattext = { enabled = false, inCombat = false, outOfCombat = false, inInstance = false, inRaid = false, inParty = false, solo = false, inBattleground = false },
      },
    },

    mover = {
      enabled = true,
      moveMode = false,
      gridSize = 8,
      snapToGrid = true,
      showGrid = true,
      showGuides = true,
      tintAlpha = 0.45,
      handleScale = 1.0,
    },
  }
}
